# -*-python-*-

from SCons.Errors import EnvironmentError

try:
    Import("env")

    test_env = env.Clone(tools = ['nose'])

    if not test_env['SYSTEM'] == 'win':
        sources = test_env.Glob('*.py')

        exclude = """
        """.split()

        sources = [source for source in sources if not source.name in exclude]

        targets = test_env.Nosetests(sources, cover_package='statiskit.core')
        Alias("test", targets)
        Alias("install", targets)
        test_env.Depends(targets, "py")
except EnvironmentError:
    Alias("test", [])
    Alias("install", [])
    pass
except Exception:
    raise
