# # -*-python-*-

Import("env")
pyenv = env.Clone(tools = ['boost_python'])

pyenv.AppendUnique(LIBS  = ['statiskit_core'])

exclude = """
""".split()

sources = [source for source in pyenv.Glob('*.*') if source.name not in exclude]

targets = pyenv.BoostPythonExtension("statiskit/core/__core", sources)
Alias("py", targets)
Alias("install", targets)

targets = pyenv.PythonPackage('statiskit')
Alias("py", targets)
Alias("install", targets)