#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > const volatile * get_pointer<class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > const volatile >(class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
}


void wrapper_254a949a22f75fcd955b7fb5973dd2cc()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::reference  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_7b8315bcbe575228be18ca7c8902f9b8)() const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator*;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_7a673f281ca45fad86314280ddc51eb8)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_0ad53328fc945f65a4885dd4c8f0eb66)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_b8a8659d2cb85da5a6b8ff9603dbd880)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_6484287f41675052a61f040866a2331d)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_555959f31bcb52849f59cd4fb479d9f7)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator+;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_6d1bd142bce15ce682325ceea08d8f34)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator+=;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_ecae5933610b59acb4a5708c55008116)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator-;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_f2c1bb9a483750cbbc758dbaa3af6996)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator-=;
    ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::reference  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< char const *, ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > >::*method_pointer_d4a08d648ade51e591d4346ce80058fd)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >::operator[];
    boost::python::class_< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > >, autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >::Type, boost::python::bases< struct ::std::iterator< struct ::std::random_access_iterator_tag, char, long int, char const *, char const & > > > class_254a949a22f75fcd955b7fb5973dd2cc("_ReverseIterator_254a949a22f75fcd955b7fb5973dd2cc", "", boost::python::no_init);
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__mul__", method_pointer_7b8315bcbe575228be18ca7c8902f9b8, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__next__", method_pointer_7a673f281ca45fad86314280ddc51eb8, boost::python::return_internal_reference<>(), "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__next__", method_pointer_0ad53328fc945f65a4885dd4c8f0eb66, "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__prev__", method_pointer_b8a8659d2cb85da5a6b8ff9603dbd880, boost::python::return_internal_reference<>(), "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__prev__", method_pointer_6484287f41675052a61f040866a2331d, "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__add__", method_pointer_555959f31bcb52849f59cd4fb479d9f7, "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__iadd__", method_pointer_6d1bd142bce15ce682325ceea08d8f34, boost::python::return_internal_reference<>(), "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__sub__", method_pointer_ecae5933610b59acb4a5708c55008116, "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__isub__", method_pointer_f2c1bb9a483750cbbc758dbaa3af6996, boost::python::return_internal_reference<>(), "");
    class_254a949a22f75fcd955b7fb5973dd2cc.def("__getitem__", method_pointer_d4a08d648ade51e591d4346ce80058fd, boost::python::return_value_policy< boost::python::return_by_value >(), "");

    if(autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >::is_class)
    {
        boost::python::implicitly_convertible< autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< char const *, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >::Type, autowig::Held< struct ::std::iterator< struct ::std::random_access_iterator_tag, char, long int, char const *, char const & > >::Type >();
    }

}