#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > const volatile * get_pointer<class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > const volatile >(class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
}


void wrapper_d906e195faad530ab7522d2cd23e0044()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_acd9a978669f59f1a52bb5545ecf1d8d)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_08d56b612e9e540286af3bc3e352f7c0)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_7baf03fc89505fcf88b0b2a22b9e72d4)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_4cc765fe70b35104b32dfe648e1bf30c)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_7dfb0e76b506523cbcc96b4f15814a9d)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator+;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_b5020d052c2157ff9a488889d4d1e16a)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator+=;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_ca40349751375c20aa36500b01c0299b)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator-;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_a77ef072783f5693acfd1afab1d26026)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator-=;
    boost::python::class_< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >, autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > >::Type, boost::python::bases< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const & > > > class_d906e195faad530ab7522d2cd23e0044("_ReverseIterator_d906e195faad530ab7522d2cd23e0044", "", boost::python::no_init);
    class_d906e195faad530ab7522d2cd23e0044.def("__next__", method_pointer_acd9a978669f59f1a52bb5545ecf1d8d, boost::python::return_internal_reference<>(), "");
    class_d906e195faad530ab7522d2cd23e0044.def("__next__", method_pointer_08d56b612e9e540286af3bc3e352f7c0, "");
    class_d906e195faad530ab7522d2cd23e0044.def("__prev__", method_pointer_7baf03fc89505fcf88b0b2a22b9e72d4, boost::python::return_internal_reference<>(), "");
    class_d906e195faad530ab7522d2cd23e0044.def("__prev__", method_pointer_4cc765fe70b35104b32dfe648e1bf30c, "");
    class_d906e195faad530ab7522d2cd23e0044.def("__add__", method_pointer_7dfb0e76b506523cbcc96b4f15814a9d, "");
    class_d906e195faad530ab7522d2cd23e0044.def("__iadd__", method_pointer_b5020d052c2157ff9a488889d4d1e16a, boost::python::return_internal_reference<>(), "");
    class_d906e195faad530ab7522d2cd23e0044.def("__sub__", method_pointer_ca40349751375c20aa36500b01c0299b, "");
    class_d906e195faad530ab7522d2cd23e0044.def("__isub__", method_pointer_a77ef072783f5693acfd1afab1d26026, boost::python::return_internal_reference<>(), "");

    if(autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > >::is_class)
    {
        boost::python::implicitly_convertible< autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > >::Type, autowig::Held< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const *, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const & > >::Type >();
    }

}