#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > const volatile * get_pointer<class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > const volatile >(class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
}


void wrapper_343986bb8bfc54f79b77d1aed96a59a4()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_f92a2c76862f5215b967a6e0b3d6a5ea)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_7fd0e640dbb05a44b31762c78caf9fe4)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_6291d160f67a50d8bcac5aa833d9ab7a)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_aea1d7c1286155ad9fc95726b83332af)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_42e96e9548605c4c871ca83c52f4db03)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator+;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_de190876f04e511697605ec702fee78b)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator+=;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_5d6c05ef4b9d5380a345e1bb1cf9de37)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator-;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_682a9d007d855dfd8913a146db366ce8)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator-=;
    boost::python::class_< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >, autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > >::Type, boost::python::bases< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > & > > > class_343986bb8bfc54f79b77d1aed96a59a4("_ReverseIterator_343986bb8bfc54f79b77d1aed96a59a4", "", boost::python::no_init);
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__next__", method_pointer_f92a2c76862f5215b967a6e0b3d6a5ea, boost::python::return_internal_reference<>(), "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__next__", method_pointer_7fd0e640dbb05a44b31762c78caf9fe4, "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__prev__", method_pointer_6291d160f67a50d8bcac5aa833d9ab7a, boost::python::return_internal_reference<>(), "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__prev__", method_pointer_aea1d7c1286155ad9fc95726b83332af, "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__add__", method_pointer_42e96e9548605c4c871ca83c52f4db03, "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__iadd__", method_pointer_de190876f04e511697605ec702fee78b, boost::python::return_internal_reference<>(), "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__sub__", method_pointer_5d6c05ef4b9d5380a345e1bb1cf9de37, "");
    class_343986bb8bfc54f79b77d1aed96a59a4.def("__isub__", method_pointer_682a9d007d855dfd8913a146db366ce8, boost::python::return_internal_reference<>(), "");

    if(autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > >::is_class)
    {
        boost::python::implicitly_convertible< autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > >::Type, autowig::Held< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > *, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > & > >::Type >();
    }

}