#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > const volatile * get_pointer<class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > const volatile >(class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
}


void wrapper_8e6936546bfb5c84966dda2c7d410e39()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_9a3c5abf96245ebe93075ff8ef302151)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_b26ce69e3bc2572d84f862268a15d3f4)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_e09b3d8359d95e8dac2fd794c272805d)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_fab9e1d93da45f7eaead2e157d9a7f14)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_7be0cdb3b1de57a8b516a53c1a7d5835)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator+;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_bb124922c1f65fdc9e7c563545d4a562)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator+=;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_26bacec1d8bc50528b6547ee6ed5e148)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator-;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::BinomialDistribution > *, ::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > > > >::*method_pointer_5bb5e7c261cf5639abca072c8104371b)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >::operator-=;
    boost::python::class_< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > >, autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > >::Type, boost::python::bases< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > & > > > class_8e6936546bfb5c84966dda2c7d410e39("_ReverseIterator_8e6936546bfb5c84966dda2c7d410e39", "", boost::python::no_init);
    class_8e6936546bfb5c84966dda2c7d410e39.def("__next__", method_pointer_9a3c5abf96245ebe93075ff8ef302151, boost::python::return_internal_reference<>(), "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__next__", method_pointer_b26ce69e3bc2572d84f862268a15d3f4, "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__prev__", method_pointer_e09b3d8359d95e8dac2fd794c272805d, boost::python::return_internal_reference<>(), "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__prev__", method_pointer_fab9e1d93da45f7eaead2e157d9a7f14, "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__add__", method_pointer_7be0cdb3b1de57a8b516a53c1a7d5835, "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__iadd__", method_pointer_bb124922c1f65fdc9e7c563545d4a562, boost::python::return_internal_reference<>(), "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__sub__", method_pointer_26bacec1d8bc50528b6547ee6ed5e148, "");
    class_8e6936546bfb5c84966dda2c7d410e39.def("__isub__", method_pointer_5bb5e7c261cf5639abca072c8104371b, boost::python::return_internal_reference<>(), "");

    if(autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > >::is_class)
    {
        boost::python::implicitly_convertible< autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > > > >::Type, autowig::Held< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > *, class ::std::shared_ptr< class ::statiskit::BinomialDistribution > & > >::Type >();
    }

}