#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > const volatile * get_pointer<class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > const volatile >(class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
}


void wrapper_ced2a8d156a759d7971cb8196d49df09()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_35182aa2ed145b26bbb2f80afe0b7b23)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_8a1c959d98595fc9bf0202b9ff495d49)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator++;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_4f20b0aa956f5bb7a65d62be42f240c2)() = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_7a477a8497a457a7a92f0da257a42e64)(int ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator--;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_0ea687f4ed9a5d30954fd2fb20818fca)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator+;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_3fc78b3a0cca54b3bb4e8385daff8ef8)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator+=;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >  (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_d1b0e2a1c22e5132ae18061d6805911b)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) const = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator-;
    class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > & (::std::reverse_iterator< ::__gnu_cxx::__normal_iterator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > const *, ::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > > > >::*method_pointer_98e0a1eb04e75434a12fd5c2da05193b)(::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::difference_type ) = &::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >::operator-=;
    boost::python::class_< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > >, autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > >::Type, boost::python::bases< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const & > > > class_ced2a8d156a759d7971cb8196d49df09("_ReverseIterator_ced2a8d156a759d7971cb8196d49df09", "", boost::python::no_init);
    class_ced2a8d156a759d7971cb8196d49df09.def("__next__", method_pointer_35182aa2ed145b26bbb2f80afe0b7b23, boost::python::return_internal_reference<>(), "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__next__", method_pointer_8a1c959d98595fc9bf0202b9ff495d49, "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__prev__", method_pointer_4f20b0aa956f5bb7a65d62be42f240c2, boost::python::return_internal_reference<>(), "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__prev__", method_pointer_7a477a8497a457a7a92f0da257a42e64, "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__add__", method_pointer_0ea687f4ed9a5d30954fd2fb20818fca, "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__iadd__", method_pointer_3fc78b3a0cca54b3bb4e8385daff8ef8, boost::python::return_internal_reference<>(), "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__sub__", method_pointer_d1b0e2a1c22e5132ae18061d6805911b, "");
    class_ced2a8d156a759d7971cb8196d49df09.def("__isub__", method_pointer_98e0a1eb04e75434a12fd5c2da05193b, boost::python::return_internal_reference<>(), "");

    if(autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > >::is_class)
    {
        boost::python::implicitly_convertible< autowig::Held< class ::std::reverse_iterator< class ::__gnu_cxx::__normal_iterator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > > > >::Type, autowig::Held< struct ::std::iterator< struct ::std::random_access_iterator_tag, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, long int, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const *, class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const & > >::Type >();
    }

}