#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > const volatile * get_pointer<class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > const volatile >(class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
    void method_decorator_461dde535a5f5b1094c89627d77748bc(class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type  param_in_0, ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  param_out)     { instance.operator[](param_in_0) = param_out; }
    void method_decorator_c977ed4420ff5d3e83233ead978c8ae2(class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type  param_in_0, ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  param_out)     { instance.at(param_in_0) = param_out; }
    void method_decorator_9364673abed45f5580837678de65cab7(class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  param_out)     { instance.front() = param_out; }
    void method_decorator_600c158cb8d25eb9a290a6af3be9ca5b(class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  param_out)     { instance.back() = param_out; }
}


void wrapper_b3093bdb770257a29e2ed491f82a342e()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_d2ce15d1d74a531fa5cd02656caf0824)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type , ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::value_type const &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::assign;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_ce9d59f736f25e9e92bb80ea5fbec71c)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_32765a358dd25417a349fe0ec58c8f67)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::max_size;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_ca47ae62b78b5032b5330d4f008be793)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::resize;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_3b60b4961e085ddbaf11c4e338a6f6d2)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type , ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::value_type const &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::resize;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_707e0337d35f51b38985234414408bf3)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::shrink_to_fit;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_9139f77520de5507a1002b71f19d744a)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::capacity;
    bool  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_df226e6f44755ea7911bceb03bd39b60)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::empty;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_cc0b44fbf50c53169e78dcea0aae20e4)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reserve;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_461dde535a5f5b1094c89627d77748bc)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::operator[];
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_b25cf307d8365b8aa5e27da89f8c150e)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type ) const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::operator[];
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_c977ed4420ff5d3e83233ead978c8ae2)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::at;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_96dafb3ed6e3535994924d8ad233f1d3)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::size_type ) const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::at;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_9364673abed45f5580837678de65cab7)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::front;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_9fca2833ce345cbe88bc77eb1237a365)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::front;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_600c158cb8d25eb9a290a6af3be9ca5b)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::back;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_d0df139542815d25bb6ef57081ce65bb)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::back;
    class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > * (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_8637126126335151af6fdebb41d234fc)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::data;
    class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > const * (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_6fd6fa275325585b9cb0facf96a96328)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::data;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_14ad97d1fcdc561bb9e43859690b5eec)(::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::value_type const &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::push_back;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_f1d522b8b96b5de4bb3d64d7462d41b3)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::pop_back;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_194a939b3021530fb4caea70de009bee)(class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::swap;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::NegativeBinomialDistribution > > >::*method_pointer_156b3644f5b55c9098fdc7a3369064ce)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >::clear;
    boost::python::class_< class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >, autowig::Held< class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > >::Type > class_b3093bdb770257a29e2ed491f82a342e("_Vector_b3093bdb770257a29e2ed491f82a342e", "", boost::python::no_init);
    class_b3093bdb770257a29e2ed491f82a342e.def(boost::python::init<  >(""));
    class_b3093bdb770257a29e2ed491f82a342e.def(boost::python::init< class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > const & >(""));
    class_b3093bdb770257a29e2ed491f82a342e.def("assign", method_pointer_d2ce15d1d74a531fa5cd02656caf0824, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("__len__", method_pointer_ce9d59f736f25e9e92bb80ea5fbec71c, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("max_size", method_pointer_32765a358dd25417a349fe0ec58c8f67, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("resize", method_pointer_ca47ae62b78b5032b5330d4f008be793, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("resize", method_pointer_3b60b4961e085ddbaf11c4e338a6f6d2, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("shrink_to_fit", method_pointer_707e0337d35f51b38985234414408bf3, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("capacity", method_pointer_9139f77520de5507a1002b71f19d744a, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("empty", method_pointer_df226e6f44755ea7911bceb03bd39b60, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("reserve", method_pointer_cc0b44fbf50c53169e78dcea0aae20e4, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("__getitem__", method_pointer_461dde535a5f5b1094c89627d77748bc, boost::python::return_internal_reference<>(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("__getitem__", autowig::method_decorator_461dde535a5f5b1094c89627d77748bc);
    class_b3093bdb770257a29e2ed491f82a342e.def("__getitem__", method_pointer_b25cf307d8365b8aa5e27da89f8c150e, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("at", method_pointer_c977ed4420ff5d3e83233ead978c8ae2, boost::python::return_internal_reference<>(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("at", autowig::method_decorator_c977ed4420ff5d3e83233ead978c8ae2);
    class_b3093bdb770257a29e2ed491f82a342e.def("at", method_pointer_96dafb3ed6e3535994924d8ad233f1d3, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("front", method_pointer_9364673abed45f5580837678de65cab7, boost::python::return_internal_reference<>(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("front", autowig::method_decorator_9364673abed45f5580837678de65cab7);
    class_b3093bdb770257a29e2ed491f82a342e.def("front", method_pointer_9fca2833ce345cbe88bc77eb1237a365, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("back", method_pointer_600c158cb8d25eb9a290a6af3be9ca5b, boost::python::return_internal_reference<>(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("back", autowig::method_decorator_600c158cb8d25eb9a290a6af3be9ca5b);
    class_b3093bdb770257a29e2ed491f82a342e.def("back", method_pointer_d0df139542815d25bb6ef57081ce65bb, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("data", method_pointer_8637126126335151af6fdebb41d234fc, boost::python::return_value_policy< boost::python::reference_existing_object >(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("data", method_pointer_6fd6fa275325585b9cb0facf96a96328, boost::python::return_value_policy< boost::python::reference_existing_object >(), "");
    class_b3093bdb770257a29e2ed491f82a342e.def("push_back", method_pointer_14ad97d1fcdc561bb9e43859690b5eec, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("pop_back", method_pointer_f1d522b8b96b5de4bb3d64d7462d41b3, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("swap", method_pointer_194a939b3021530fb4caea70de009bee, "");
    class_b3093bdb770257a29e2ed491f82a342e.def("clear", method_pointer_156b3644f5b55c9098fdc7a3369064ce, "");

    struct vector_b3093bdb770257a29e2ed491f82a342e_from_python
    {
        vector_b3093bdb770257a29e2ed491f82a342e_from_python()
        {
            boost::python::converter::registry::push_back(
                &convertible,
                &construct,
                boost::python::type_id< class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > >());
        }

        static void* convertible(PyObject* obj_ptr)
        { return obj_ptr; }

        static void construct(PyObject* obj_ptr, boost::python::converter::rvalue_from_python_stage1_data* data)
        {
            boost::python::handle<> obj_iter(PyObject_GetIter(obj_ptr));
            void* storage = ((boost::python::converter::rvalue_from_python_storage< class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > > >*)data)->storage.bytes;
            new (storage) class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >();
            data->convertible = storage;
            class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >& result = *((class ::std::vector< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > > >*)storage);
            unsigned int i = 0;
            for(;; i++)
            {
                boost::python::handle<> py_elem_hdl(boost::python::allow_null(PyIter_Next(obj_iter.get())));
                if(PyErr_Occurred())
                { boost::python::throw_error_already_set(); }
                if(!py_elem_hdl.get())
                { break; }
                boost::python::object py_elem_obj(py_elem_hdl);
                result.push_back((class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution > )(boost::python::extract< class ::std::shared_ptr< class ::statiskit::NegativeBinomialDistribution >  >(py_elem_obj)));
            }
        }
    };

    vector_b3093bdb770257a29e2ed491f82a342e_from_python();
}