#include "_core.h"


#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > const volatile * get_pointer<class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > const volatile >(class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > const volatile *c) { return c; }
}
    #endif
#endif

namespace autowig
{
    void method_decorator_02f8f3c077fb5684aa88b1a402dae774(class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type  param_in_0, ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  param_out)     { instance.operator[](param_in_0) = param_out; }
    void method_decorator_34bfbed2cdeb5bce9c9f7eaf4e61f8f4(class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type  param_in_0, ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  param_out)     { instance.at(param_in_0) = param_out; }
    void method_decorator_09b3473d4739567eaea54e156ee60ef6(class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  param_out)     { instance.front() = param_out; }
    void method_decorator_80ca3ef7c7e956d498738e6d14e0ff20(class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > & instance, ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  param_out)     { instance.back() = param_out; }
}


void wrapper_83d2907497ba508c97d9b5d2afea62ab()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_22d3cf33cc695347ae3840e401b9a8e2)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type , ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::value_type const &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::assign;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_89d1f88c74345486a8ad24b775c53228)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_8a3815301e635a5db59950f23a402f0c)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::max_size;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_1c6532ef0f875db588f9aa6bed7f8f5c)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::resize;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_37da3cd6d24853e68d69b0a4cd2db86b)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type , ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::value_type const &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::resize;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_26c002c946c35a39acdba2a5cd39a6f2)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::shrink_to_fit;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_67b6547bf51c5de9bf548e735f1d05cf)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::capacity;
    bool  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_4136dbd85e395c8095d3d8652457effc)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::empty;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_ffaff936641f577fb32e2108480101c8)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reserve;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_02f8f3c077fb5684aa88b1a402dae774)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::operator[];
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_cfed4906979953c89861d008e717544c)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type ) const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::operator[];
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_34bfbed2cdeb5bce9c9f7eaf4e61f8f4)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type ) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::at;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_c9b3ddeb6f075b829e906b94ad421951)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::size_type ) const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::at;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_09b3473d4739567eaea54e156ee60ef6)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::front;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_9a6f05f983775941add42345608e4085)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::front;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_80ca3ef7c7e956d498738e6d14e0ff20)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::back;
    ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::const_reference  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_383f2ad9105a5142a1e7d96a3a98bcac)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::back;
    class ::std::shared_ptr< class ::statiskit::BinomialDistribution > * (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_816ee5fe5d3e528d8a45df9095f27824)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::data;
    class ::std::shared_ptr< class ::statiskit::BinomialDistribution > const * (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_37aee23e49125cd29e602041832fcf27)() const = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::data;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_3bd85724860858b4837b229473534225)(::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::value_type const &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::push_back;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_0e22e6923ec058fa932a80f757c36d20)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::pop_back;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_ad9fe1f4a80656039467738444dc6817)(class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > &) = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::swap;
    void  (::std::vector< ::std::shared_ptr< ::statiskit::BinomialDistribution >, ::std::allocator< ::std::shared_ptr< ::statiskit::BinomialDistribution > > >::*method_pointer_f7544652268c5733bc3b7e927da54569)() = &::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >::clear;
    boost::python::class_< class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >, autowig::Held< class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > >::Type > class_83d2907497ba508c97d9b5d2afea62ab("_Vector_83d2907497ba508c97d9b5d2afea62ab", "", boost::python::no_init);
    class_83d2907497ba508c97d9b5d2afea62ab.def(boost::python::init<  >(""));
    class_83d2907497ba508c97d9b5d2afea62ab.def(boost::python::init< class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > const & >(""));
    class_83d2907497ba508c97d9b5d2afea62ab.def("assign", method_pointer_22d3cf33cc695347ae3840e401b9a8e2, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("__len__", method_pointer_89d1f88c74345486a8ad24b775c53228, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("max_size", method_pointer_8a3815301e635a5db59950f23a402f0c, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("resize", method_pointer_1c6532ef0f875db588f9aa6bed7f8f5c, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("resize", method_pointer_37da3cd6d24853e68d69b0a4cd2db86b, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("shrink_to_fit", method_pointer_26c002c946c35a39acdba2a5cd39a6f2, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("capacity", method_pointer_67b6547bf51c5de9bf548e735f1d05cf, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("empty", method_pointer_4136dbd85e395c8095d3d8652457effc, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("reserve", method_pointer_ffaff936641f577fb32e2108480101c8, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("__getitem__", method_pointer_02f8f3c077fb5684aa88b1a402dae774, boost::python::return_internal_reference<>(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("__getitem__", autowig::method_decorator_02f8f3c077fb5684aa88b1a402dae774);
    class_83d2907497ba508c97d9b5d2afea62ab.def("__getitem__", method_pointer_cfed4906979953c89861d008e717544c, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("at", method_pointer_34bfbed2cdeb5bce9c9f7eaf4e61f8f4, boost::python::return_internal_reference<>(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("at", autowig::method_decorator_34bfbed2cdeb5bce9c9f7eaf4e61f8f4);
    class_83d2907497ba508c97d9b5d2afea62ab.def("at", method_pointer_c9b3ddeb6f075b829e906b94ad421951, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("front", method_pointer_09b3473d4739567eaea54e156ee60ef6, boost::python::return_internal_reference<>(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("front", autowig::method_decorator_09b3473d4739567eaea54e156ee60ef6);
    class_83d2907497ba508c97d9b5d2afea62ab.def("front", method_pointer_9a6f05f983775941add42345608e4085, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("back", method_pointer_80ca3ef7c7e956d498738e6d14e0ff20, boost::python::return_internal_reference<>(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("back", autowig::method_decorator_80ca3ef7c7e956d498738e6d14e0ff20);
    class_83d2907497ba508c97d9b5d2afea62ab.def("back", method_pointer_383f2ad9105a5142a1e7d96a3a98bcac, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("data", method_pointer_816ee5fe5d3e528d8a45df9095f27824, boost::python::return_value_policy< boost::python::reference_existing_object >(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("data", method_pointer_37aee23e49125cd29e602041832fcf27, boost::python::return_value_policy< boost::python::reference_existing_object >(), "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("push_back", method_pointer_3bd85724860858b4837b229473534225, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("pop_back", method_pointer_0e22e6923ec058fa932a80f757c36d20, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("swap", method_pointer_ad9fe1f4a80656039467738444dc6817, "");
    class_83d2907497ba508c97d9b5d2afea62ab.def("clear", method_pointer_f7544652268c5733bc3b7e927da54569, "");

    struct vector_83d2907497ba508c97d9b5d2afea62ab_from_python
    {
        vector_83d2907497ba508c97d9b5d2afea62ab_from_python()
        {
            boost::python::converter::registry::push_back(
                &convertible,
                &construct,
                boost::python::type_id< class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > >());
        }

        static void* convertible(PyObject* obj_ptr)
        { return obj_ptr; }

        static void construct(PyObject* obj_ptr, boost::python::converter::rvalue_from_python_stage1_data* data)
        {
            boost::python::handle<> obj_iter(PyObject_GetIter(obj_ptr));
            void* storage = ((boost::python::converter::rvalue_from_python_storage< class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > > >*)data)->storage.bytes;
            new (storage) class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >();
            data->convertible = storage;
            class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >& result = *((class ::std::vector< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >, class ::std::allocator< class ::std::shared_ptr< class ::statiskit::BinomialDistribution > > >*)storage);
            unsigned int i = 0;
            for(;; i++)
            {
                boost::python::handle<> py_elem_hdl(boost::python::allow_null(PyIter_Next(obj_iter.get())));
                if(PyErr_Occurred())
                { boost::python::throw_error_already_set(); }
                if(!py_elem_hdl.get())
                { break; }
                boost::python::object py_elem_obj(py_elem_hdl);
                result.push_back((class ::std::shared_ptr< class ::statiskit::BinomialDistribution > )(boost::python::extract< class ::std::shared_ptr< class ::statiskit::BinomialDistribution >  >(py_elem_obj)));
            }
        }
    };

    vector_83d2907497ba508c97d9b5d2afea62ab_from_python();
}