# -*-python-*-

Import("env")
pyenv = env.Clone(tools = ['pybind11'])
pyenv.AppendUnique(LIBS  = ['statiskit_core'])
if pyenv['SYSTEM'] == 'linux':
    pyenv.AppendUnique(CCFLAGS = ['-Wno-ignored-attributes'])

exclude = """
""".split()

sources = [source for source in pyenv.Glob('*.*') if source.name not in exclude]
targets = pyenv.PyBind11Extension("../statiskit/core/__core", sources)
Alias("py", targets)
Alias("install", targets)
pyenv.Depends(targets, "cpp")

targets = pyenv.PythonPackage(statiskit = '../statiskit')
Alias("py", targets)
Alias("install", targets)
pyenv.Depends(targets, "cpp")

targets = pyenv.PythonPackage(statiskit='../statiskit')
Alias("py", targets)
Alias("install", targets)
pyenv.Depends(targets, "cpp")