#include "_core.h"

bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_611291dafb3051bbaa7cd984f387adf3)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::get_pi;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_e1de62eaf40658b590608adf03557e01)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::set_pi;
struct ::statiskit::DiscreteMultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_b269070c1d205c64b5e0853cf19ec3cf)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::get_default_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_e7e1827c761b5570975b1b52f3bd536b)(struct ::statiskit::DiscreteMultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::set_default_estimator;
struct ::statiskit::DiscreteMultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_ea4d01fdeeda534db75dddaf81b17170)(::statiskit::Index const &)const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::get_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_c5223b56abc6508e9fa54a64c734f1ab)(::statiskit::Index const &, struct ::statiskit::DiscreteMultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::set_estimator;
struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution > const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_2c371f625fa7556c8c9f3db12ffac853)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::get_initializator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_681e97f54b7c548b932e8bdf0d3c8cf9)(struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution > const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::set_initializator;
bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_a60f61482e1a5f728a02d241230443be)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::get_limit;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::DiscreteMultivariateDistribution >, ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::*method_pointer_604964a9c834575dabaaf7e259691fa6)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator::set_limit;

namespace autowig {
}

void wrapper_7a72df81b8e3525a981c66a31496b8f4(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator, autowig::HolderType< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator >::Type, struct ::statiskit::OptimizationEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution > *, struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator > class_7a72df81b8e3525a981c66a31496b8f4(module, "Estimator", "");
    class_7a72df81b8e3525a981c66a31496b8f4.def(pybind11::init<  >());
    class_7a72df81b8e3525a981c66a31496b8f4.def(pybind11::init< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::DiscreteMultivariateDistribution >, struct ::statiskit::DiscreteMultivariateDistributionEstimation >::Estimator const & >());
    class_7a72df81b8e3525a981c66a31496b8f4.def("get_pi", method_pointer_611291dafb3051bbaa7cd984f387adf3, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("set_pi", method_pointer_e1de62eaf40658b590608adf03557e01, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("get_default_estimator", method_pointer_b269070c1d205c64b5e0853cf19ec3cf, pybind11::return_value_policy::reference_internal, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("set_default_estimator", method_pointer_e7e1827c761b5570975b1b52f3bd536b, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("get_estimator", method_pointer_ea4d01fdeeda534db75dddaf81b17170, pybind11::return_value_policy::reference_internal, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("set_estimator", method_pointer_c5223b56abc6508e9fa54a64c734f1ab, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("get_initializator", method_pointer_2c371f625fa7556c8c9f3db12ffac853, pybind11::return_value_policy::reference_internal, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("set_initializator", method_pointer_681e97f54b7c548b932e8bdf0d3c8cf9, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("get_limit", method_pointer_a60f61482e1a5f728a02d241230443be, "");
    class_7a72df81b8e3525a981c66a31496b8f4.def("set_limit", method_pointer_604964a9c834575dabaaf7e259691fa6, "");

}