#include "_core.h"

struct ::statiskit::MultivariateConditionalDistributionEstimation & (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation > >::*method_pointer_fb5d95975a3e57a7a8c385713e978fc1)()const= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::operator*;
::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation > >::*method_pointer_c8e54408cbc157b8ab8bf7580911596a)()const= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::get;
::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation > >::*method_pointer_702afb447638560fb2b2ae59a2d79630)()= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::release;
void  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation > >::*method_pointer_26088893f5dc5d17a580519a8a89bba6)(::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::pointer )= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::reset;
void  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation > >::*method_pointer_7a0ac1bca7425f9db90bb6e0b452df11)(class ::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > > &)= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > >::swap;

namespace autowig {
    void method_decorator_fb5d95975a3e57a7a8c385713e978fc1(class ::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation > > const & instance, const struct ::statiskit::MultivariateConditionalDistributionEstimation & param_out) { instance.operator*() = param_out; }
}

void wrapper_62ba3b73a1c356bcacfb0c66e927e78d(pybind11::module& module)
{

}