#include "_core.h"

struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator & (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_abad22c20ada5a209e05d29b54a0823d)()const= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_9095696393c3573d94a77df38ddee6ba)()const= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_43f2ff7b083755839d29fd4c190f2074)()= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_570b7dcad2b95b4097b750ce41f53ed7)(::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_5155d9a739915411ab33dce92f8ad4df)(class ::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_abad22c20ada5a209e05d29b54a0823d(class ::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator > > const & instance, const struct ::statiskit::UnivariateConditionalDistributionEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_d358a39c74145ef4b6d844aec605e715(pybind11::module& module)
{

}