#include "_core.h"

struct ::statiskit::UnivariateDistributionEstimation::Estimator & (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation::Estimator > >::*method_pointer_d940dfc3527a5e7ea30b7c7f815c15ad)()const= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation::Estimator > >::*method_pointer_708e930123eb514d9bf638a4021c655d)()const= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation::Estimator > >::*method_pointer_5d0aa6819945597e83f5eeb7dcc57f66)()= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation::Estimator > >::*method_pointer_60e7bfda9a8c57c8a19de8eeb8f95c07)(::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation::Estimator > >::*method_pointer_599ec8a0ced65d54a1503c17bdfe5781)(class ::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_d940dfc3527a5e7ea30b7c7f815c15ad(class ::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation::Estimator > > const & instance, const struct ::statiskit::UnivariateDistributionEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_117864e1dfe65915bf10502e182e5502(pybind11::module& module)
{

}