#include "_core.h"

bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_26f222aa3cad5a8aaf61d3e79d0c17de)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::get_pi;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_6f81f5a958e45a48a0a37f109160c757)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::set_pi;
struct ::statiskit::CategoricalMultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_252014055f075e3a9d269e4943082f6a)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::get_default_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_2fa7cacd4fc05114901a23c5f97dbb79)(struct ::statiskit::CategoricalMultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::set_default_estimator;
struct ::statiskit::CategoricalMultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_94882fda899c581681dbf4ab2b105331)(::statiskit::Index const &)const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::get_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_840a3e0ea0cb515ca2012a3ab01b7bc5)(::statiskit::Index const &, struct ::statiskit::CategoricalMultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::set_estimator;
struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution > const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_faba4f7f8c85542b81cf425676c5593d)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::get_initializator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_b5cf8e266b93574696657345ec695b46)(struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution > const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::set_initializator;
bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_9eb188d84a885936a8f44f00e82c06de)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::get_limit;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::CategoricalMultivariateDistribution >, ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::*method_pointer_de4b878fef8d55ecb58bca6be0410015)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator::set_limit;

namespace autowig {
}

void wrapper_5e703a4587815486b6950405a411169b(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator, autowig::HolderType< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator >::Type, struct ::statiskit::OptimizationEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution > *, struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator > class_5e703a4587815486b6950405a411169b(module, "Estimator", "");
    class_5e703a4587815486b6950405a411169b.def(pybind11::init<  >());
    class_5e703a4587815486b6950405a411169b.def(pybind11::init< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::CategoricalMultivariateDistribution >, struct ::statiskit::CategoricalMultivariateDistributionEstimation >::Estimator const & >());
    class_5e703a4587815486b6950405a411169b.def("get_pi", method_pointer_26f222aa3cad5a8aaf61d3e79d0c17de, "");
    class_5e703a4587815486b6950405a411169b.def("set_pi", method_pointer_6f81f5a958e45a48a0a37f109160c757, "");
    class_5e703a4587815486b6950405a411169b.def("get_default_estimator", method_pointer_252014055f075e3a9d269e4943082f6a, pybind11::return_value_policy::reference_internal, "");
    class_5e703a4587815486b6950405a411169b.def("set_default_estimator", method_pointer_2fa7cacd4fc05114901a23c5f97dbb79, "");
    class_5e703a4587815486b6950405a411169b.def("get_estimator", method_pointer_94882fda899c581681dbf4ab2b105331, pybind11::return_value_policy::reference_internal, "");
    class_5e703a4587815486b6950405a411169b.def("set_estimator", method_pointer_840a3e0ea0cb515ca2012a3ab01b7bc5, "");
    class_5e703a4587815486b6950405a411169b.def("get_initializator", method_pointer_faba4f7f8c85542b81cf425676c5593d, pybind11::return_value_policy::reference_internal, "");
    class_5e703a4587815486b6950405a411169b.def("set_initializator", method_pointer_b5cf8e266b93574696657345ec695b46, "");
    class_5e703a4587815486b6950405a411169b.def("get_limit", method_pointer_9eb188d84a885936a8f44f00e82c06de, "");
    class_5e703a4587815486b6950405a411169b.def("set_limit", method_pointer_de4b878fef8d55ecb58bca6be0410015, "");

}