#include "_core.h"

struct ::statiskit::SingularDistributionEstimation::Estimator & (::std::unique_ptr< ::statiskit::SingularDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::SingularDistributionEstimation::Estimator > >::*method_pointer_e691984a4d3f5bc7b85ea1fd5e9c3233)()const= &::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::SingularDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::SingularDistributionEstimation::Estimator > >::*method_pointer_b093bd43f5fa5185b6e89753893bbb26)()const= &::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::SingularDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::SingularDistributionEstimation::Estimator > >::*method_pointer_bf7d1619c1e35ce390a7864c06837e7d)()= &::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::SingularDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::SingularDistributionEstimation::Estimator > >::*method_pointer_8b29eadeac8b572ab8bd079e8a9aae32)(::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::SingularDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::SingularDistributionEstimation::Estimator > >::*method_pointer_35a94cf21d9350baaa2e531ff79c191d)(class ::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_e691984a4d3f5bc7b85ea1fd5e9c3233(class ::std::unique_ptr< struct ::statiskit::SingularDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::SingularDistributionEstimation::Estimator > > const & instance, const struct ::statiskit::SingularDistributionEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_1ae28b9397ee5736a45e106e0eb3d8f9(pybind11::module& module)
{

}