#include "_core.h"

bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_fcc221ad0b225b9ba6b5140d83d85b40)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::get_pi;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_261e1ab6113a55c3bdf324189362713d)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::set_pi;
struct ::statiskit::ContinuousMultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_467ad7b3ba435c158c6472cc09bcc13d)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::get_default_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_bd4665a580ed55b5b481c5daf10a5f55)(struct ::statiskit::ContinuousMultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::set_default_estimator;
struct ::statiskit::ContinuousMultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_8b6f9074d908561fa6954acd7216528d)(::statiskit::Index const &)const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::get_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_91fe1f5e1a415df9b04dd56d938429ea)(::statiskit::Index const &, struct ::statiskit::ContinuousMultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::set_estimator;
struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution > const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_52f44246c523501590bb1099d660e731)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::get_initializator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_7daf3e46b86a5b14a6bbc6e4b42bb979)(struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution > const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::set_initializator;
bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_cb661dcffa6e5daf85e53f11ab9175a1)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::get_limit;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::ContinuousMultivariateDistribution >, ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::*method_pointer_3f39d5da208659e49e6675a474a6437c)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator::set_limit;

namespace autowig {
}

void wrapper_f3dab438657054798b20b872db63311a(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator, autowig::HolderType< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator >::Type, struct ::statiskit::OptimizationEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution > *, struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator > class_f3dab438657054798b20b872db63311a(module, "Estimator", "");
    class_f3dab438657054798b20b872db63311a.def(pybind11::init<  >());
    class_f3dab438657054798b20b872db63311a.def(pybind11::init< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::ContinuousMultivariateDistribution >, struct ::statiskit::ContinuousMultivariateDistributionEstimation >::Estimator const & >());
    class_f3dab438657054798b20b872db63311a.def("get_pi", method_pointer_fcc221ad0b225b9ba6b5140d83d85b40, "");
    class_f3dab438657054798b20b872db63311a.def("set_pi", method_pointer_261e1ab6113a55c3bdf324189362713d, "");
    class_f3dab438657054798b20b872db63311a.def("get_default_estimator", method_pointer_467ad7b3ba435c158c6472cc09bcc13d, pybind11::return_value_policy::reference_internal, "");
    class_f3dab438657054798b20b872db63311a.def("set_default_estimator", method_pointer_bd4665a580ed55b5b481c5daf10a5f55, "");
    class_f3dab438657054798b20b872db63311a.def("get_estimator", method_pointer_8b6f9074d908561fa6954acd7216528d, pybind11::return_value_policy::reference_internal, "");
    class_f3dab438657054798b20b872db63311a.def("set_estimator", method_pointer_91fe1f5e1a415df9b04dd56d938429ea, "");
    class_f3dab438657054798b20b872db63311a.def("get_initializator", method_pointer_52f44246c523501590bb1099d660e731, pybind11::return_value_policy::reference_internal, "");
    class_f3dab438657054798b20b872db63311a.def("set_initializator", method_pointer_7daf3e46b86a5b14a6bbc6e4b42bb979, "");
    class_f3dab438657054798b20b872db63311a.def("get_limit", method_pointer_cb661dcffa6e5daf85e53f11ab9175a1, "");
    class_f3dab438657054798b20b872db63311a.def("set_limit", method_pointer_3f39d5da208659e49e6675a474a6437c, "");

}