#include "_core.h"

struct ::statiskit::UnivariateDistributionEstimation & (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation > >::*method_pointer_a8ed34dc8ace5242973b3ad0aa61c017)()const= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::operator*;
::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation > >::*method_pointer_f03d8028d76c50b49ef54d8da1e444e6)()const= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::get;
::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation > >::*method_pointer_209060b43485518a8a4fdfa7e5f95c56)()= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::release;
void  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation > >::*method_pointer_99718d4c412f5e6298c5e2ffe7a74c40)(::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::pointer )= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::reset;
void  (::std::unique_ptr< ::statiskit::UnivariateDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateDistributionEstimation > >::*method_pointer_5ec25eaeb0f659eda21574d1af963340)(class ::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > > &)= &::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > >::swap;

namespace autowig {
    void method_decorator_a8ed34dc8ace5242973b3ad0aa61c017(class ::std::unique_ptr< struct ::statiskit::UnivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateDistributionEstimation > > const & instance, const struct ::statiskit::UnivariateDistributionEstimation & param_out) { instance.operator*() = param_out; }
}

void wrapper_edfb27681f195343b523e5b949187dba(pybind11::module& module)
{

}