#include "_core.h"

bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_48331612c6b050d297a965bc08d631e3)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::get_pi;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_e5bb55005097548cb43c61526b3fe4f3)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::set_pi;
struct ::statiskit::CategoricalUnivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_bbe4939ea1255cb4a7d50a7a7f59d9dc)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::get_default_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_c81eb4cebb5e59838ebccc17b5caff5d)(struct ::statiskit::CategoricalUnivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::set_default_estimator;
struct ::statiskit::CategoricalUnivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_aa6ef24a31ff5f168defe1f7d18eba74)(::statiskit::Index const &)const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::get_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_5b98ab0e08715fbbb37a547541a919e2)(::statiskit::Index const &, struct ::statiskit::CategoricalUnivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::set_estimator;
struct ::statiskit::CategoricalUnivariateMixtureDistribution const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_fa34b875735c576889b76188583fbdeb)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::get_initializator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_f6577bcc0efd58f68abf9c4d0e57e6fa)(struct ::statiskit::CategoricalUnivariateMixtureDistribution const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::set_initializator;
bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_5eb2a331eb3b53f38545cac4bf37c385)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::get_limit;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::CategoricalUnivariateMixtureDistribution, ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::*method_pointer_1670b3a1a1b15e52808578df65548524)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator::set_limit;

namespace autowig {
}

void wrapper_446f651133d55eebbb2e7b65c75f4477(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator, autowig::HolderType< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator >::Type, struct ::statiskit::OptimizationEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution *, struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator > class_446f651133d55eebbb2e7b65c75f4477(module, "Estimator", "");
    class_446f651133d55eebbb2e7b65c75f4477.def(pybind11::init<  >());
    class_446f651133d55eebbb2e7b65c75f4477.def(pybind11::init< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::CategoricalUnivariateMixtureDistribution, struct ::statiskit::CategoricalUnivariateDistributionEstimation >::Estimator const & >());
    class_446f651133d55eebbb2e7b65c75f4477.def("get_pi", method_pointer_48331612c6b050d297a965bc08d631e3, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("set_pi", method_pointer_e5bb55005097548cb43c61526b3fe4f3, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("get_default_estimator", method_pointer_bbe4939ea1255cb4a7d50a7a7f59d9dc, pybind11::return_value_policy::reference_internal, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("set_default_estimator", method_pointer_c81eb4cebb5e59838ebccc17b5caff5d, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("get_estimator", method_pointer_aa6ef24a31ff5f168defe1f7d18eba74, pybind11::return_value_policy::reference_internal, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("set_estimator", method_pointer_5b98ab0e08715fbbb37a547541a919e2, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("get_initializator", method_pointer_fa34b875735c576889b76188583fbdeb, pybind11::return_value_policy::reference_internal, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("set_initializator", method_pointer_f6577bcc0efd58f68abf9c4d0e57e6fa, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("get_limit", method_pointer_5eb2a331eb3b53f38545cac4bf37c385, "");
    class_446f651133d55eebbb2e7b65c75f4477.def("set_limit", method_pointer_1670b3a1a1b15e52808578df65548524, "");

}