#include "_core.h"

class ::statiskit::MultivariateConditionalData::Generator & (::std::unique_ptr< ::statiskit::MultivariateConditionalData::Generator, ::std::default_delete< ::statiskit::MultivariateConditionalData::Generator > >::*method_pointer_ddab4138863850aeac674399882ccad5)()const= &::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::operator*;
::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateConditionalData::Generator, ::std::default_delete< ::statiskit::MultivariateConditionalData::Generator > >::*method_pointer_15d92ff6598654b9b1396a7e20cc02b1)()const= &::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::get;
::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateConditionalData::Generator, ::std::default_delete< ::statiskit::MultivariateConditionalData::Generator > >::*method_pointer_202a534e4ebc54959a10b84cfb2f35ba)()= &::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::release;
void  (::std::unique_ptr< ::statiskit::MultivariateConditionalData::Generator, ::std::default_delete< ::statiskit::MultivariateConditionalData::Generator > >::*method_pointer_dbe0faf17f915649bf7c02706a277f95)(::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::pointer )= &::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::reset;
void  (::std::unique_ptr< ::statiskit::MultivariateConditionalData::Generator, ::std::default_delete< ::statiskit::MultivariateConditionalData::Generator > >::*method_pointer_88e24ea6394f586aabb57770a3d4ad28)(class ::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > > &)= &::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > >::swap;

namespace autowig {
    void method_decorator_ddab4138863850aeac674399882ccad5(class ::std::unique_ptr< class ::statiskit::MultivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::MultivariateConditionalData::Generator > > const & instance, const class ::statiskit::MultivariateConditionalData::Generator & param_out) { instance.operator*() = param_out; }
}

void wrapper_9c9b0b8265215a57b48807e0fc9938ba(pybind11::module& module)
{

}