#include "_core.h"

struct ::statiskit::MultivariateDispersionEstimation::Estimator & (::std::unique_ptr< ::statiskit::MultivariateDispersionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDispersionEstimation::Estimator > >::*method_pointer_08bf751b26e954a4b5cfac4607d60bd8)()const= &::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateDispersionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDispersionEstimation::Estimator > >::*method_pointer_a33d3987c2975a5994db9f779d6c69ea)()const= &::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateDispersionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDispersionEstimation::Estimator > >::*method_pointer_79e96b93f2c558e7a241e48ba7407b50)()= &::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::MultivariateDispersionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDispersionEstimation::Estimator > >::*method_pointer_9d290f4fd2215fadbf78bbec8ca7dac7)(::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::MultivariateDispersionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDispersionEstimation::Estimator > >::*method_pointer_285aff3fd5ca575a97ae89a6af53c573)(class ::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_08bf751b26e954a4b5cfac4607d60bd8(class ::std::unique_ptr< struct ::statiskit::MultivariateDispersionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDispersionEstimation::Estimator > > const & instance, const struct ::statiskit::MultivariateDispersionEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_a5987d3cf2915a0aa8ed90e4c5f1f64f(pybind11::module& module)
{

}