#include "_core.h"

struct ::statiskit::MultivariateDistributionEstimation::Estimator & (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation::Estimator > >::*method_pointer_e9a2ee0b9f6a5f6195dc7a1c934b35b2)()const= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation::Estimator > >::*method_pointer_7741bbc646ca5780bc53e17466faeb1c)()const= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation::Estimator > >::*method_pointer_1de494578d955f15b0784ab837bd8f8c)()= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation::Estimator > >::*method_pointer_eafdd2ff91935df290ca3903fa7e7cfa)(::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation::Estimator > >::*method_pointer_97efcd4663dc5c20ba14db3a52c9cf76)(class ::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_e9a2ee0b9f6a5f6195dc7a1c934b35b2(class ::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation::Estimator > > const & instance, const struct ::statiskit::MultivariateDistributionEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_6286fa427e2b5074b726466691e9713a(pybind11::module& module)
{

}