#include "_core.h"

void  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_4404f31006fe555bad4e42b9c70df207)(::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size_type , ::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::value_type const &)= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::assign;
::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size_type  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_7649ac26f87b5e3aa6951d208a52d19e)()const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size;
::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size_type  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_1569dcf243b151e5a8927e40b27abb03)()const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::max_size;
::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size_type  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_640d5059827d58e9a833c390a13cdc25)()const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::capacity;
bool  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_ce4bfbe243db58d1974e59f2b60efd4a)()const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::empty;
void  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_1e4e9fa2fc565e33ab0f3e2811e1a3c5)(::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size_type )= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::reserve;
::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_f457ae0f0e735133b35567a0f150c812)(::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::size_type )const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::at;
::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_0302eaea8603571ab5677a4c78b1df15)()const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::front;
::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_b7d4466c42245df2b5d9b4e0c0114fc0)()const= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::back;
void  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_6a4a4bde0222578e8831672c70e8c3e3)(::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::value_type const &)= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::push_back;
void  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_cd3b61e847205a5fbc0f5c1ac4a877c9)()= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::pop_back;
void  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_6475b00342f95688b247f001b1e5216e)(class ::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > > &)= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::swap;
void  (::std::vector< ::statiskit::ContinuousUnivariateDistribution *, ::std::allocator< ::statiskit::ContinuousUnivariateDistribution * > >::*method_pointer_c8c2a6f96a7b5497ae370358ff647233)()= &::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >::clear;

namespace autowig {
}

void wrapper_67870dc7ea665794a91fa84ca05aecb0(pybind11::module& module)
{

    pybind11::class_<class ::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > >, autowig::HolderType< class ::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > > >::Type > class_67870dc7ea665794a91fa84ca05aecb0(module, "_Vector_67870dc7ea665794a91fa84ca05aecb0", "");
    class_67870dc7ea665794a91fa84ca05aecb0.def(pybind11::init<  >());
    class_67870dc7ea665794a91fa84ca05aecb0.def(pybind11::init< class ::std::vector< struct ::statiskit::ContinuousUnivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousUnivariateDistribution * > > const & >());
    class_67870dc7ea665794a91fa84ca05aecb0.def("assign", method_pointer_4404f31006fe555bad4e42b9c70df207, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("__len__", method_pointer_7649ac26f87b5e3aa6951d208a52d19e, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("max_size", method_pointer_1569dcf243b151e5a8927e40b27abb03, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("capacity", method_pointer_640d5059827d58e9a833c390a13cdc25, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("empty", method_pointer_ce4bfbe243db58d1974e59f2b60efd4a, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("reserve", method_pointer_1e4e9fa2fc565e33ab0f3e2811e1a3c5, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("at", method_pointer_f457ae0f0e735133b35567a0f150c812, pybind11::return_value_policy::reference_internal, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("front", method_pointer_0302eaea8603571ab5677a4c78b1df15, pybind11::return_value_policy::reference_internal, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("back", method_pointer_b7d4466c42245df2b5d9b4e0c0114fc0, pybind11::return_value_policy::reference_internal, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("push_back", method_pointer_6a4a4bde0222578e8831672c70e8c3e3, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("pop_back", method_pointer_cd3b61e847205a5fbc0f5c1ac4a877c9, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("swap", method_pointer_6475b00342f95688b247f001b1e5216e, "");
    class_67870dc7ea665794a91fa84ca05aecb0.def("clear", method_pointer_c8c2a6f96a7b5497ae370358ff647233, "");

}