#include "_core.h"

void  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_16a927cb4a6657e2bf1eb0fb06313040)(::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size_type , ::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::value_type const &)= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::assign;
::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size_type  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_65948b788f485d72bf9c4e1af5672101)()const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size;
::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size_type  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_dbe07b728eb55b71a0e8e32ce2eca50c)()const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::max_size;
::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size_type  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_48c8906e5f0b50b4a374a152c2a3115a)()const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::capacity;
bool  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_615427bdd2035d878b060d294508ab6b)()const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::empty;
void  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_c7d80e04df925f3ea83883c382d0a837)(::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size_type )= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::reserve;
::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_0105132f7817576385d4f88cabb5407e)(::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::size_type )const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::at;
::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_0ad8e422019f5f6dabf19063ae8df9dd)()const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::front;
::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_2c3a9f542f585e8abd5cdcb25ed93cb9)()const= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::back;
void  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_8489ea8ee68c5991915557916d7002d3)(::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::value_type const &)= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::push_back;
void  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_52dcc9305e3258a48c34bc8bbf3808f8)()= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::pop_back;
void  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_357f2fe1af7751a2b4c9d4d2c6cd40c1)(class ::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > > &)= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::swap;
void  (::std::vector< ::statiskit::CategoricalMultivariateDistribution *, ::std::allocator< ::statiskit::CategoricalMultivariateDistribution * > >::*method_pointer_55b0ab8bd57850e3b5b525906a7c12c4)()= &::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >::clear;

namespace autowig {
}

void wrapper_ee054e76c90f582f9e07cdff4cd63eda(pybind11::module& module)
{

    pybind11::class_<class ::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > >, autowig::HolderType< class ::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > > >::Type > class_ee054e76c90f582f9e07cdff4cd63eda(module, "_Vector_ee054e76c90f582f9e07cdff4cd63eda", "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def(pybind11::init<  >());
    class_ee054e76c90f582f9e07cdff4cd63eda.def(pybind11::init< class ::std::vector< struct ::statiskit::CategoricalMultivariateDistribution *, class ::std::allocator< struct ::statiskit::CategoricalMultivariateDistribution * > > const & >());
    class_ee054e76c90f582f9e07cdff4cd63eda.def("assign", method_pointer_16a927cb4a6657e2bf1eb0fb06313040, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("__len__", method_pointer_65948b788f485d72bf9c4e1af5672101, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("max_size", method_pointer_dbe07b728eb55b71a0e8e32ce2eca50c, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("capacity", method_pointer_48c8906e5f0b50b4a374a152c2a3115a, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("empty", method_pointer_615427bdd2035d878b060d294508ab6b, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("reserve", method_pointer_c7d80e04df925f3ea83883c382d0a837, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("at", method_pointer_0105132f7817576385d4f88cabb5407e, pybind11::return_value_policy::reference_internal, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("front", method_pointer_0ad8e422019f5f6dabf19063ae8df9dd, pybind11::return_value_policy::reference_internal, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("back", method_pointer_2c3a9f542f585e8abd5cdcb25ed93cb9, pybind11::return_value_policy::reference_internal, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("push_back", method_pointer_8489ea8ee68c5991915557916d7002d3, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("pop_back", method_pointer_52dcc9305e3258a48c34bc8bbf3808f8, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("swap", method_pointer_357f2fe1af7751a2b4c9d4d2c6cd40c1, "");
    class_ee054e76c90f582f9e07cdff4cd63eda.def("clear", method_pointer_55b0ab8bd57850e3b5b525906a7c12c4, "");

}