#include "_core.h"

bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_8e90587550ba59fd9b55fac637085ce9)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::get_pi;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_9b672d4df6905210a93e76476da93061)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::set_pi;
struct ::statiskit::DiscreteUnivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_588eec9bbde25b03a86b36bce9f06aec)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::get_default_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_8b481e7fd71351a7a17a03d2bfbf53dc)(struct ::statiskit::DiscreteUnivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::set_default_estimator;
struct ::statiskit::DiscreteUnivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_ce92b40f53c151df85206128e4ccf99b)(::statiskit::Index const &)const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::get_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_08205fa989e857638a6088d3c7c36f3f)(::statiskit::Index const &, struct ::statiskit::DiscreteUnivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::set_estimator;
struct ::statiskit::DiscreteUnivariateMixtureDistribution const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_1ada7f6a10495cd48cdf989b099c7ba1)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::get_initializator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_9da82349b5da573fb99ab92feaa1c4eb)(struct ::statiskit::DiscreteUnivariateMixtureDistribution const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::set_initializator;
bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_d762829d60c15b8a8ad32fe454342c4e)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::get_limit;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::DiscreteUnivariateMixtureDistribution, ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::*method_pointer_5f023c643a4557f9949f3684dcb40d72)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator::set_limit;

namespace autowig {
}

void wrapper_eb3cd0df0cd558acb42631cfa3f9a172(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator, autowig::HolderType< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator >::Type, struct ::statiskit::OptimizationEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution *, struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator > class_eb3cd0df0cd558acb42631cfa3f9a172(module, "Estimator", "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def(pybind11::init<  >());
    class_eb3cd0df0cd558acb42631cfa3f9a172.def(pybind11::init< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::DiscreteUnivariateMixtureDistribution, struct ::statiskit::DiscreteUnivariateDistributionEstimation >::Estimator const & >());
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("get_pi", method_pointer_8e90587550ba59fd9b55fac637085ce9, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("set_pi", method_pointer_9b672d4df6905210a93e76476da93061, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("get_default_estimator", method_pointer_588eec9bbde25b03a86b36bce9f06aec, pybind11::return_value_policy::reference_internal, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("set_default_estimator", method_pointer_8b481e7fd71351a7a17a03d2bfbf53dc, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("get_estimator", method_pointer_ce92b40f53c151df85206128e4ccf99b, pybind11::return_value_policy::reference_internal, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("set_estimator", method_pointer_08205fa989e857638a6088d3c7c36f3f, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("get_initializator", method_pointer_1ada7f6a10495cd48cdf989b099c7ba1, pybind11::return_value_policy::reference_internal, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("set_initializator", method_pointer_9da82349b5da573fb99ab92feaa1c4eb, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("get_limit", method_pointer_d762829d60c15b8a8ad32fe454342c4e, "");
    class_eb3cd0df0cd558acb42631cfa3f9a172.def("set_limit", method_pointer_5f023c643a4557f9949f3684dcb40d72, "");

}