#include "_core.h"

struct ::statiskit::UnivariateLocationEstimation::Estimator & (::std::unique_ptr< ::statiskit::UnivariateLocationEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateLocationEstimation::Estimator > >::*method_pointer_5f44fe47089d58ce8a031102a341157a)()const= &::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateLocationEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateLocationEstimation::Estimator > >::*method_pointer_36b69502ca5455a28bc78882881bf56d)()const= &::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateLocationEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateLocationEstimation::Estimator > >::*method_pointer_01f78f3c97ad560ebef9019a7aba42c9)()= &::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::UnivariateLocationEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateLocationEstimation::Estimator > >::*method_pointer_086b9fa9c6d6547da43c541d4c8c678f)(::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::UnivariateLocationEstimation::Estimator, ::std::default_delete< ::statiskit::UnivariateLocationEstimation::Estimator > >::*method_pointer_97158cccf1835a6e912e0bb13fa5cf9b)(class ::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_5f44fe47089d58ce8a031102a341157a(class ::std::unique_ptr< struct ::statiskit::UnivariateLocationEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::UnivariateLocationEstimation::Estimator > > const & instance, const struct ::statiskit::UnivariateLocationEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_aa517e9d14595c32b4bf797f0280ed1f(pybind11::module& module)
{

}