#include "_core.h"

class ::statiskit::UnivariateConditionalData::Generator & (::std::unique_ptr< ::statiskit::UnivariateConditionalData::Generator, ::std::default_delete< ::statiskit::UnivariateConditionalData::Generator > >::*method_pointer_2aa7a34c635a59ef9528f5b57459e7f6)()const= &::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::operator*;
::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateConditionalData::Generator, ::std::default_delete< ::statiskit::UnivariateConditionalData::Generator > >::*method_pointer_bda781d3af075f859bc342d293946587)()const= &::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::get;
::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateConditionalData::Generator, ::std::default_delete< ::statiskit::UnivariateConditionalData::Generator > >::*method_pointer_51c192a0ea5b5d0f9cf162d430f968ed)()= &::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::release;
void  (::std::unique_ptr< ::statiskit::UnivariateConditionalData::Generator, ::std::default_delete< ::statiskit::UnivariateConditionalData::Generator > >::*method_pointer_e6ed2998c4a55b24b8915f7e1d3c155d)(::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::pointer )= &::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::reset;
void  (::std::unique_ptr< ::statiskit::UnivariateConditionalData::Generator, ::std::default_delete< ::statiskit::UnivariateConditionalData::Generator > >::*method_pointer_dc92bf9c9025520189648570e27ccb60)(class ::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > > &)= &::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > >::swap;

namespace autowig {
    void method_decorator_2aa7a34c635a59ef9528f5b57459e7f6(class ::std::unique_ptr< class ::statiskit::UnivariateConditionalData::Generator, struct ::std::default_delete< class ::statiskit::UnivariateConditionalData::Generator > > const & instance, const class ::statiskit::UnivariateConditionalData::Generator & param_out) { instance.operator*() = param_out; }
}

void wrapper_99243b0a36d95168b8a85b4b4999e459(pybind11::module& module)
{

}