#include "_core.h"

struct ::statiskit::MultivariateDistributionEstimation & (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation > >::*method_pointer_f93c1e93a0245b05b5e5bf3026df3134)()const= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::operator*;
::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation > >::*method_pointer_439ffa6b446352169fb1467ec652acc3)()const= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::get;
::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation > >::*method_pointer_a068f77d9db65e1182afb6738912439d)()= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::release;
void  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation > >::*method_pointer_bfd88355a54556fb8298ff8c3b0511df)(::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::pointer )= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::reset;
void  (::std::unique_ptr< ::statiskit::MultivariateDistributionEstimation, ::std::default_delete< ::statiskit::MultivariateDistributionEstimation > >::*method_pointer_eb8289867abf565eb022e4d49cb7e2a7)(class ::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > > &)= &::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > >::swap;

namespace autowig {
    void method_decorator_f93c1e93a0245b05b5e5bf3026df3134(class ::std::unique_ptr< struct ::statiskit::MultivariateDistributionEstimation, struct ::std::default_delete< struct ::statiskit::MultivariateDistributionEstimation > > const & instance, const struct ::statiskit::MultivariateDistributionEstimation & param_out) { instance.operator*() = param_out; }
}

void wrapper_97ddfd5be73a5e91b93724af3ea449cd(pybind11::module& module)
{

}