#include "_core.h"

struct ::statiskit::UnivariateConditionalDistributionEstimation & (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation > >::*method_pointer_0f7c30ba060752d18b4c9cf79178bc8f)()const= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::operator*;
::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation > >::*method_pointer_ee01c860098d56c085a348a15bedd8a7)()const= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::get;
::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::pointer  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation > >::*method_pointer_ed3ce06c133c575994c22b1ab4ccc139)()= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::release;
void  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation > >::*method_pointer_5eb8ad8c2ebe5ced939b411d3fb3b1b9)(::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::pointer )= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::reset;
void  (::std::unique_ptr< ::statiskit::UnivariateConditionalDistributionEstimation, ::std::default_delete< ::statiskit::UnivariateConditionalDistributionEstimation > >::*method_pointer_2e2ff2d0745f5ff3b6470856a098bf3a)(class ::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > > &)= &::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > >::swap;

namespace autowig {
    void method_decorator_0f7c30ba060752d18b4c9cf79178bc8f(class ::std::unique_ptr< struct ::statiskit::UnivariateConditionalDistributionEstimation, struct ::std::default_delete< struct ::statiskit::UnivariateConditionalDistributionEstimation > > const & instance, const struct ::statiskit::UnivariateConditionalDistributionEstimation & param_out) { instance.operator*() = param_out; }
}

void wrapper_ceecfdda95b55b7c9ffa26c45ca90aef(pybind11::module& module)
{

}