#include "_core.h"

void  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_572afe9f5b815944a96c44b07e362aea)(::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size_type , ::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::value_type const &)= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::assign;
::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size_type  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_38d07b50758a58bb87f682a2d859edc5)()const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size;
::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size_type  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_398aaead4ee750409cbe5f1331745a5a)()const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::max_size;
::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size_type  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_5e5118a5461154daa965f11e167d2070)()const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::capacity;
bool  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_a377b0390b65509b9c71510f782ca199)()const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::empty;
void  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_3b4f419050be58b5ad99d8e62aca5c63)(::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size_type )= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::reserve;
::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_3c62ad09c99f5aa6b2c7df833b0a54bd)(::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::size_type )const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::at;
::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_e1ab4a82ce105a3e9b27f9e69de5bd70)()const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::front;
::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::const_reference  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_e615afbdaa5e57b38d259aaa00d9969b)()const= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::back;
void  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_8c6b4b6af5bd5ec994a16fa166b8b5ba)(::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::value_type const &)= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::push_back;
void  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_ff5807704a2e5ff7bef76770f40b3371)()= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::pop_back;
void  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_2074276592eb542181fc14ae221179a7)(class ::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > > &)= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::swap;
void  (::std::vector< ::statiskit::ContinuousMultivariateDistribution *, ::std::allocator< ::statiskit::ContinuousMultivariateDistribution * > >::*method_pointer_22c911e25b275ad5a0337d581e30b4d8)()= &::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >::clear;

namespace autowig {
}

void wrapper_19ec6a1f261852b5b192c3cbc4571d78(pybind11::module& module)
{

    pybind11::class_<class ::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > >, autowig::HolderType< class ::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > > >::Type > class_19ec6a1f261852b5b192c3cbc4571d78(module, "_Vector_19ec6a1f261852b5b192c3cbc4571d78", "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def(pybind11::init<  >());
    class_19ec6a1f261852b5b192c3cbc4571d78.def(pybind11::init< class ::std::vector< struct ::statiskit::ContinuousMultivariateDistribution *, class ::std::allocator< struct ::statiskit::ContinuousMultivariateDistribution * > > const & >());
    class_19ec6a1f261852b5b192c3cbc4571d78.def("assign", method_pointer_572afe9f5b815944a96c44b07e362aea, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("__len__", method_pointer_38d07b50758a58bb87f682a2d859edc5, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("max_size", method_pointer_398aaead4ee750409cbe5f1331745a5a, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("capacity", method_pointer_5e5118a5461154daa965f11e167d2070, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("empty", method_pointer_a377b0390b65509b9c71510f782ca199, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("reserve", method_pointer_3b4f419050be58b5ad99d8e62aca5c63, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("at", method_pointer_3c62ad09c99f5aa6b2c7df833b0a54bd, pybind11::return_value_policy::reference_internal, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("front", method_pointer_e1ab4a82ce105a3e9b27f9e69de5bd70, pybind11::return_value_policy::reference_internal, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("back", method_pointer_e615afbdaa5e57b38d259aaa00d9969b, pybind11::return_value_policy::reference_internal, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("push_back", method_pointer_8c6b4b6af5bd5ec994a16fa166b8b5ba, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("pop_back", method_pointer_ff5807704a2e5ff7bef76770f40b3371, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("swap", method_pointer_2074276592eb542181fc14ae221179a7, "");
    class_19ec6a1f261852b5b192c3cbc4571d78.def("clear", method_pointer_22c911e25b275ad5a0337d581e30b4d8, "");

}