#include "_core.h"

struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator & (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_b693b91fd62c5c3c95dbeda328fc8440)()const= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::operator*;
::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_cf70e442e608532c817b7838ef7e8ac0)()const= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::get;
::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_17d60d6d59a45563b7fb589ec48acf6b)()= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_badf9df6281a5194b9de6d5288998703)(::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::pointer )= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, ::std::default_delete< ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::*method_pointer_df52b78a962555cca2e598d0984ffe4e)(class ::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > > &)= &::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > >::swap;

namespace autowig {
    void method_decorator_b693b91fd62c5c3c95dbeda328fc8440(class ::std::unique_ptr< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator, struct ::std::default_delete< struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator > > const & instance, const struct ::statiskit::MultivariateConditionalDistributionEstimation::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_8c51a578c55d5bdd9eb4e60d4581366b(pybind11::module& module)
{

}