#include "_core.h"

bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_7c695267884e5ac5b3fd0b5f3a3003d9)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::get_pi;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_7d64041b9f77529080eb343676d726ae)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::set_pi;
struct ::statiskit::MultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_1dd26c7ab62e5134949241d9d57a5399)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::get_default_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_d64bb47602a350f4abb5d24b7fc66771)(struct ::statiskit::MultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::set_default_estimator;
struct ::statiskit::MultivariateDistributionEstimation::Estimator const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_fd041d6ff7b050cbae13f50a5def440e)(::statiskit::Index const &)const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::get_estimator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_fcd8b6ff608656f58112043d99228386)(::statiskit::Index const &, struct ::statiskit::MultivariateDistributionEstimation::Estimator const *)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::set_estimator;
struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution > const * (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_af89fce79dcd59c3a537cf3d1be956a1)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::get_initializator;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_c5c8e0ca20e4521a972b3da4e150813e)(struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution > const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::set_initializator;
bool  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_84d6003896d157788b4e7c311dabc47e)()const= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::get_limit;
void  (::statiskit::MixtureDistributionEMEstimation< ::statiskit::MultivariateMixtureDistribution< ::statiskit::MultivariateDistribution >, ::statiskit::MultivariateDistributionEstimation >::Estimator::*method_pointer_43b4be65cfdc5c82a1a507a7d20827bc)(bool const &)= &::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator::set_limit;

namespace autowig {
}

void wrapper_5d11528f24755a879438133d5708e545(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator, autowig::HolderType< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator >::Type, struct ::statiskit::OptimizationEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution > *, struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator > class_5d11528f24755a879438133d5708e545(module, "Estimator", "");
    class_5d11528f24755a879438133d5708e545.def(pybind11::init<  >());
    class_5d11528f24755a879438133d5708e545.def(pybind11::init< class ::statiskit::MixtureDistributionEMEstimation< struct ::statiskit::MultivariateMixtureDistribution< struct ::statiskit::MultivariateDistribution >, struct ::statiskit::MultivariateDistributionEstimation >::Estimator const & >());
    class_5d11528f24755a879438133d5708e545.def("get_pi", method_pointer_7c695267884e5ac5b3fd0b5f3a3003d9, "");
    class_5d11528f24755a879438133d5708e545.def("set_pi", method_pointer_7d64041b9f77529080eb343676d726ae, "");
    class_5d11528f24755a879438133d5708e545.def("get_default_estimator", method_pointer_1dd26c7ab62e5134949241d9d57a5399, pybind11::return_value_policy::reference_internal, "");
    class_5d11528f24755a879438133d5708e545.def("set_default_estimator", method_pointer_d64bb47602a350f4abb5d24b7fc66771, "");
    class_5d11528f24755a879438133d5708e545.def("get_estimator", method_pointer_fd041d6ff7b050cbae13f50a5def440e, pybind11::return_value_policy::reference_internal, "");
    class_5d11528f24755a879438133d5708e545.def("set_estimator", method_pointer_fcd8b6ff608656f58112043d99228386, "");
    class_5d11528f24755a879438133d5708e545.def("get_initializator", method_pointer_af89fce79dcd59c3a537cf3d1be956a1, pybind11::return_value_policy::reference_internal, "");
    class_5d11528f24755a879438133d5708e545.def("set_initializator", method_pointer_c5c8e0ca20e4521a972b3da4e150813e, "");
    class_5d11528f24755a879438133d5708e545.def("get_limit", method_pointer_84d6003896d157788b4e7c311dabc47e, "");
    class_5d11528f24755a879438133d5708e545.def("set_limit", method_pointer_43b4be65cfdc5c82a1a507a7d20827bc, "");

}