__all__ = []

# Import dependency decorator modules
import statiskit.linalg._linalg
import statiskit.stl._stl

# Import Boost.Python module
import __core

# Resolve scopes
__core.statiskit.MeanEstimation.Estimator = __core.statiskit._mean_estimation.Estimator
__core.statiskit.UnivariateData.Generator = __core.statiskit._univariate_data.Generator
__core.statiskit.UnivariateDistributionEstimation.Estimator = __core.statiskit._univariate_distribution_estimation.Estimator
__core.statiskit.MultivariateDistributionEstimation.Estimator = __core.statiskit._multivariate_distribution_estimation.Estimator
__core.statiskit.SizeError.size_type = __core.statiskit._size_error.size_type
__core.statiskit.MultivariateData.Generator = __core.statiskit._multivariate_data.Generator
__core.statiskit.VarianceEstimation.Estimator = __core.statiskit._variance_estimation.Estimator
__core.statiskit.CategoricalMultivariateDistributionEstimation.Estimator = __core.statiskit._categorical_multivariate_distribution_estimation.Estimator
__core.statiskit.NaturalVarianceEstimation.Estimator = __core.statiskit._natural_variance_estimation.Estimator
__core.statiskit.NaturalMeanEstimation.Estimator = __core.statiskit._natural_mean_estimation.Estimator
__core.statiskit.ContinuousMultivariateDistributionEstimation.Estimator = __core.statiskit._continuous_multivariate_distribution_estimation.Estimator
__core.statiskit.ContinuousUnivariateDistributionEstimation.Estimator = __core.statiskit._continuous_univariate_distribution_estimation.Estimator
__core.statiskit.DiscreteMultivariateDistributionEstimation.Estimator = __core.statiskit._discrete_multivariate_distribution_estimation.Estimator
__core.statiskit.CategoricalUnivariateDistributionEstimation.Estimator = __core.statiskit._categorical_univariate_distribution_estimation.Estimator
__core.statiskit.DiscreteUnivariateDistributionEstimation.Estimator = __core.statiskit._discrete_univariate_distribution_estimation.Estimator
__core.statiskit.RegularUnivariateHistogramDistributionSlopeHeuristicSelection.Estimator = __core.statiskit._regular_univariate_histogram_distribution_slope_heuristic_selection.Estimator
__core.statiskit.BinomialDistributionMMEstimation.Estimator = __core.statiskit._binomial_distribution_mm_estimation.Estimator
__core.statiskit.NegativeBinomialDistributionMMEstimation.Estimator = __core.statiskit._negative_binomial_distribution_mm_estimation.Estimator
__core.statiskit.PoissonDistributionMLEstimation.Estimator = __core.statiskit._poisson_distribution_ml_estimation.Estimator
__core.statiskit.IrregularUnivariateHistogramDistributionSlopeHeuristicSelection.Estimator = __core.statiskit._irregular_univariate_histogram_distribution_slope_heuristic_selection.Estimator
__core.statiskit.NormalDistributionMLEstimation.Estimator = __core.statiskit._normal_distribution_ml_estimation.Estimator
__core.statiskit.UnivariateHistogramDistributionEstimation.Estimator = __core.statiskit._univariate_histogram_distribution_estimation.Estimator
__core.statiskit._OptimizationEstimation_66ba790876ea5d25be923643f217b67a.Estimator = __core.statiskit.__optimization_estimation_66ba790876ea5d25be923643f217b67a.Estimator
__core.statiskit._OptimizationEstimation_6ab41d8aa0095175b6da7190fc953a97.Estimator = __core.statiskit.__optimization_estimation_6ab41d8aa0095175b6da7190fc953a97.Estimator
__core.statiskit.NegativeBinomialDistributionMLEstimation.Estimator = __core.statiskit._negative_binomial_distribution_ml_estimation.Estimator
__core.statiskit.BinomialDistributionMLEstimation.Estimator = __core.statiskit._binomial_distribution_ml_estimation.Estimator

# Group template specializations
__core.statiskit._SlopeHeuristicSelection = [__core.statiskit._SlopeHeuristicSelection_9ba0310efd9c520c8c9e6cb4ff8fb1a4]
__core.statiskit._LazyEstimation = [__core.statiskit._LazyEstimation_281a291cf9465a1e9af25cbee1cf5bad, __core.statiskit._LazyEstimation_40c631b5a67d5748bbfdeaa0beedb4e0, __core.statiskit._LazyEstimation_49e18be963b9503a942009b04ff7e676, __core.statiskit._LazyEstimation_db760ff53e0e5dca8e558b09ed12163c, __core.statiskit._LazyEstimation_ef99412d87545a1391d9c6cbb66e08e8]
__core.statiskit._UnivariateFrequencyDistribution = [__core.statiskit._UnivariateFrequencyDistribution_a4463e49d7865a6497ec20612e342cbe]
__core.statiskit._ActiveEstimation = [__core.statiskit._ActiveEstimation_19ee605677815ce58ebdc169d44e3d8c, __core.statiskit._ActiveEstimation_281622f2e8fd576dae1b13441146f58b, __core.statiskit._ActiveEstimation_36c99cd43c5c5fb8abeb0fd1ca103ac8, __core.statiskit._ActiveEstimation_66ea0b28087057f5abc6f26dadfb4c15, __core.statiskit._ActiveEstimation_f490fbe6298d5af89adf9098e57be3d4]
__core.std._Vector = [__core.std._Vector_160b713997e259caa9b19848803d29f1]
__core.statiskit._OptimizationEstimation = [__core.statiskit._OptimizationEstimation_66ba790876ea5d25be923643f217b67a, __core.statiskit._OptimizationEstimation_6ab41d8aa0095175b6da7190fc953a97]

# Define aliases
__core.statiskit.UnivariateData.SampleSpaceType = __core.statiskit.UnivariateSampleSpace
__core.statiskit.UnivariateData.EventType = __core.statiskit.UnivariateEvent
__core.statiskit.UnivariateDistributionEstimation.DataType = __core.statiskit.UnivariateData
__core.statiskit.UnivariateDistributionEstimation.EstimatedType = __core.statiskit.UnivariateDistribution
__core.statiskit.UnivariateDistributionEstimation.Estimator.EstimationType = __core.statiskit.UnivariateDistributionEstimation
__core.statiskit.MultivariateDistributionEstimation.DataType = __core.statiskit.MultivariateData
__core.statiskit.MultivariateDistributionEstimation.EstimatedType = __core.statiskit.MultivariateDistribution
__core.statiskit.MultivariateDistributionEstimation.MarginalType = __core.statiskit.UnivariateDistributionEstimation
__core.statiskit.MultivariateDistribution.MarginalType = __core.statiskit.UnivariateDistribution
__core.statiskit.MultivariateDistributionEstimation.Estimator.EstimationType = __core.statiskit.MultivariateDistributionEstimation
__core.statiskit.MultivariateDistributionEstimation.Estimator.MarginalType = __core.statiskit.UnivariateDistributionEstimation
__core.statiskit.UnivariateConditionalDistribution.ResponseType = __core.statiskit.UnivariateDistribution
__core.statiskit.MultivariateData.SampleSpaceType = __core.statiskit.MultivariateSampleSpace
__core.statiskit.MultivariateData.EventType = __core.statiskit.MultivariateEvent
__core.statiskit.DiscreteUnivariateDistribution.EventType = __core.statiskit.DiscreteEvent
__core.statiskit.ContinuousUnivariateConditionalDistribution.ResponseType = __core.statiskit.ContinuousUnivariateDistribution
__core.statiskit.CategoricalUnivariateConditionalDistribution.ResponseType = __core.statiskit.CategoricalUnivariateDistribution
__core.statiskit.DiscreteMultivariateDistribution.MarginalType = __core.statiskit.DiscreteUnivariateDistribution
__core.statiskit.DiscreteUnivariateConditionalDistribution.ResponseType = __core.statiskit.DiscreteUnivariateDistribution
__core.statiskit.DiscreteEvent.DistributionType = __core.statiskit.DiscreteUnivariateDistribution
__core.statiskit.ContinuousUnivariateDistribution.EventType = __core.statiskit.ContinuousEvent
__core.statiskit.ContinuousMultivariateDistribution.MarginalType = __core.statiskit.ContinuousUnivariateDistribution
__core.statiskit.ContinuousEvent.DistributionType = __core.statiskit.ContinuousUnivariateDistribution
__core.statiskit.DiscreteMultivariateDistributionEstimation.MarginalType = __core.statiskit.DiscreteUnivariateDistributionEstimation
__core.statiskit.CategoricalMultivariateDistribution.MarginalType = __core.statiskit.CategoricalUnivariateDistribution
__core.statiskit.CategoricalEvent.ValueType = statiskit.stl.__stl.std._BasicString_448c20257e485acda59dc59305fceb58
__core.statiskit.CategoricalEvent.DistributionType = __core.statiskit.CategoricalUnivariateDistribution
__core.statiskit.CategoricalUnivariateDistribution.EventType = __core.statiskit.CategoricalEvent
__core.statiskit.CategoricalMultivariateDistributionEstimation.MarginalType = __core.statiskit.CategoricalUnivariateDistributionEstimation
__core.statiskit.ContinuousMultivariateDistributionEstimation.MarginalType = __core.statiskit.ContinuousUnivariateDistributionEstimation
